#basically this is a deployment for the escalation-api service
#it is used to deploy the escalation-api service to the kubernetes cluster

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: escalation-api
#   labels:
#     app: escalation-api
#     version: v1.0.0
# spec:
#   r